# Project Information
site_name: CTF Tools
site_description: CTF 军火库
site_author: CTF Wiki Team
site_url: https://ctf-wiki.github.io/ctf-tools/

# Repository
repo_name: 'ctf-wiki/ctf-tools'
repo_url: 'https://github.com/ctf-wiki/ctf-tools'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 CTF Wiki Team'

# Contents
nav:
  - CTF Tools:
    - Getting started 开始使用: index.md
    - Collections 工具合集: collections.md
    - Environment 环境配置: environment.md
    - Misc 杂项: misc.md
    - Crypto 密码学: crypto.md
    - Reverse 逆向工程: reverse.md
    - Pwn 二进制漏洞挖掘: pwn.md
    - Web 网站应用: web.md
    - Papers 会议: papers.md


# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'gavel'
  favicon: '_static/img/favicon.png'
  feature:
    tabs: true
  font:
    text: 'Source Sans Pro'
    code: 'Source Code Pro'

# Customization
extra:
  search:
    language: 'jp'

extra_javascript:
    - '_static/js/extra.js'
    - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
